apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonweb
  template:
    metadata:
      labels:
        app: pythonweb
    spec:
      containers:
        - name: pythonflask
          image: chinmayir/python_flask12:v1
          ports:
            - containerPort: 5000
